version: '3'
services:
  nifi:
    image: apache/nifi:latest
    restart: on-failure
    ports:
      - 8080:8080
    environment:
      - NIFI_WEB_HTTP_PORT=8080
    volumes:
      - C:\nifi:/opt/data