version: '2.2'
services:
  1_node_es_node:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.3
    container_name: 1_node_es_cluster
    environment:
      - node.name=1_node_es
      - discovery.type=single-node
      - cluster.name=1_node_es_cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - 1_node_es_cluster_volume:/usr/share/elasticsearch/data:rw
    ports:
      - 9200:9200

volumes:
  1_node_es_cluster_volume:
    name: 1_node_es_node_volume
    driver: local
